### ISSUE TITLE
worldCoors and headSize

### ISSUE THREAD

**Issue by changjo** [Naman-ntc/Pytorch-Human-Pose-Estimation#1]
Hi,
I was wondering what `worldCoors` and `headSize` represent and how they are made.
Thanks.

**Comment by Naman-ntc** [comment]
Hi,
Thanks for the interest!
In calculation of PCKh we use head-sizes as bboxes. MPII has provided head bboxes and these mat files belong those head size estimates. Please find [link](https://github.com/Naman-ntc/Pytorch-Human-Pose-Estimation/blob/98bc0930c38919b11f6582d0178a343c1a6af90b/metrics.py#L49
) where head sizes are used
I could have merged the .mat into annot.h5 files but I'm lazy I guess!
I will do that sometime in future.
Hope it helps!

**Comment by changjo** [comment]
I see. Thanks.
