### ISSUE TITLE
Question on DeepPose

### ISSUE THREAD

**Issue by oliverzzm** [Naman-ntc/Pytorch-Human-Pose-Estimation#10]
Your implementation just includes stage 1 of deep pose, but leave cascade part out,don't you?
I read the paper but did not quite understand how training is done for stage 2 and afterwards?
How is training data for stage 2 generated? Do we need to first wait stage 1 to be trained and run stage 1 on the training data to produce a coarse estimation and use that estimation to generate patches for stage 2?

**Comment by Naman-ntc** [comment]
Yes you are right I have left the cascading out.
I had the same doubts and chose to not implement it. You may find it helpful to contact the authors about their specific design choice.

**Comment by iamharsha1999** [comment]
Despite leaving Stage 2 (the cascading part) were you be able to reproduce fine results as that of paper ?
