### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by ZhuoerLyu** [Naman-ntc/Pytorch-Human-Pose-Estimation#11]
Hi there,

Thanks for the amazing work and I really appreciate that! I was wondering if you are going to post a demo like using pictures, videos or web_cam? If so, that would be awesome!

Thank you again!

**Comment by Naman-ntc** [comment]
Thanks for the interest and your kind words! I would like to post a demo but I am currently working on 2 research projects and therefore can't find time for it immediately. I will however try to do this soon

**Comment by ZhuoerLyu** [comment]
Thank you!

**Comment by antithing** [comment]
@ZhuoerLyu @Naman-ntc , sorry to open this old question, did either of you manage to put a demo together for a single image or camera input?

Thanks!

**Comment by Naman-ntc** [comment]
Hi, I have not been able to build a demo. But it should actually be very simple to build it as the code is very modular. Please see a rough guideline on how to run inference #3 .
Also, check out the screenshot added in #8 -- it seems to be on right track on how to run inference
