### ISSUE TITLE
where is train.h5?

### ISSUE THREAD

**Issue by electronicliujiang** [Naman-ntc/Pytorch-Human-Pose-Estimation#12]
thanks for your code!!
I can't find your train.h5. Where I can find this?  in your model.zip?

**Comment by electronicliujiang** [comment]
I have found this  thank you!!

**Comment by electronicliujiang** [comment]
How to achieve visualization？For example, key point detection visualization of pictures and videos?

**Comment by Naman-ntc** [comment]
Hi, thanks for interest in this work and sorry I do not have the visualization code formatted and arranged properly so I can't gaurentee its correctness. However you can find [this](https://github.com/xingyizhou/pytorch-pose-hg-3d/blob/373f4b755d5d78ffc2bdfe2326cfe70ffb4d90aa/src/lib/utils/debugger.py#L7) code and suit it to your requirements!

**Comment by electronicliujiang** [comment]
Hello my friend! I have some question.
Currently, I have been able to implement some visual operations, but they are all based on the mpii dataset. I would like to ask, how to check the key points on my own data set, my data set does not have s (scale) and c (center), how to set these two parameters?




------------------ 原始邮件 ------------------
发件人: "Naman Jain"<notifications@github.com>;
发送时间: 2019年10月4日(星期五) 晚上8:12
收件人: "Naman-ntc/Pytorch-Human-Pose-Estimation"<Pytorch-Human-Pose-Estimation@noreply.github.com>;
抄送: "657361488"<657361488@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Naman-ntc/Pytorch-Human-Pose-Estimation] where is train.h5?(#12)




Hi, thanks for interest in this work and sorry I do not have the visualization code formatted and arranged properly so I can't gaurentee its correctness. However you can find this code and suit it to your requirements!

**Comment by Naman-ntc** [comment]
Hi, I don't think there is any easy option. In case you have gt. skeleon coordinates you can develop rought center and scale of person but otherwise you will need a trained detector to get rough annotations for your dataset
