### ISSUE TITLE
Reproducing Results - StackedHourGlass on COCO

### ISSUE THREAD

**Issue by progvasu** [Naman-ntc/Pytorch-Human-Pose-Estimation#13]
Hi, 

I tried reproducing the results for StackedHourGlass model on COCO dataset using the pretrained weights but the PCK I got on COCO's validation dataset is 68.5

Am I missing something?

**Comment by progvasu** [comment]
@Naman-ntc I just noticed that the epoch number in the pre-trained weights file is 3...

Is it possible you might have uploaded the wrong pre-trained weights file for StackedHourGlass trained on COCO?

**Comment by Naman-ntc** [comment]
Hi, thanks for interest in my work. I'm afraid I have likely uploaded wrong file if the epoch number is 3!
I will try to look for the original model although I have not worked on this project since 8 months and am occupied somewhere else.

**Comment by progvasu** [comment]
Thanks for your reply @Naman-ntc 

If you get time for finding the original model it would be of great help...
