### ISSUE TITLE
One bug about "python main.py"

### ISSUE THREAD

**Issue by ZP-Guo** [Naman-ntc/Pytorch-Human-Pose-Estimation#14]
Thank you so much for your cod. @Naman-ntc I have the code of the Stacked Hourglass Net, but it uses lua,not Python. So your code is very import for me.
However I meet a problem when I "python main.py" recently. it dose not work. The last line in bug is `ImportError: Building module datasets.COCO.nms.gpu_nms failed:['ImportError:/home/dev0/.pyxbld/lib.linux-x86_64-3.6/datasets/COCO/nms/gpu_nms.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _nms\n']`. 
I have not this bug at first. It is the second. When the first bug comes, I use `import pyximport
pyximport.install()`, install pyxbld and copy some files in ./dataset/COCO/nms/ to somewhere and. And I do it. But this bug make me sad. So I really need your help.
PS. My command is `python main.py -DataConfig ./conf/datasets/coco.defconf -ModelConfig ./conf/models/StackedHourGlass.defconf `, and the bug is 
![image](https://user-images.githubusercontent.com/22268127/67267595-34152580-f4e5-11e9-9cd1-e1b4e320cb46.png).
Waitting in hope for your reply. Thanks so much.

**Comment by Naman-ntc** [comment]
Hi, Thanks for the interest.
You might want to check [this](https://github.com/Naman-ntc/Pytorch-Human-Pose-Estimation/issues/8) issue. The problem is with dataloader for COCO dataset as it requires GPU to build! You can maybe remove the corresponding dependencies for running your experiments till then

**Comment by ZP-Guo** [comment]
> Hi, Thanks for the interest.
> You might want to check [this](https://github.com/Naman-ntc/Pytorch-Human-Pose-Estimation/issues/8) issue. The problem is with dataloader for COCO dataset as it requires GPU to build! You can maybe remove the corresponding dependencies for running your experiments till then

Maybe my ability to understand is so bad. So sorry. Maybe the issue you provided does not work. Because I have 2 GTX 1080 GPUs and Ubuntu 16.0 and other nets can run on my PC by using GPUs.
I am so pleased to receive your reply because it is my first time to discuss a problem 😝 . Thanks so much.

**Comment by Naman-ntc** [comment]
Hi,
I can't exactly understand cause for the error. My guess is you didn''t build files for COCO dataloader according to [this link](https://github.com/Microsoft/human-pose-estimation.pytorch#quick-start) (**point 5**). Can you confirm this

**Comment by ZP-Guo** [comment]
Thanks for your reply @Naman-ntc !
Let me try my best to get your suggestion. Your code is based on the Simple Baselines [https://github.com/Microsoft/human-pose-estimation.pytorch#quick-start](url), and I need to finish the step 5: "make" in the "lib" file. So am I right?

**Comment by Naman-ntc** [comment]
Yeah, I use their COCO dataloader and you would need to build it before running the code

**Comment by ZP-Guo** [comment]
> Yeah, I use their COCO dataloader and you would need to build it before running the code

I want to say thank you for your patience and your code, though my problem has not been solved. :joy:
