### ISSUE TITLE
Where is  the implementation about T step?

### ISSUE THREAD

**Issue by tjusxh** [Naman-ntc/Pytorch-Human-Pose-Estimation#15]
In paper "Human Pose Estimation with Iterative Error Feedback", T is the nuber of correction steps taken by the model. I didn't find the detail in the code. Please help me, thanks very much.

**Comment by Naman-ntc** [comment]
Hi,
Sorry for the delay, I am busy with some other projects right now. Unfortunately we have not implemented iterative error feedback paper. We tried implemented long back but could not get satisfactory results. I want to implement the work in future but right now I don't have time to delve into it.
Closing the issue, feel free to open it up again!
