### ISSUE TITLE
What does the nModules mean？

### ISSUE THREAD

**Issue by wyao1459** [Naman-ntc/Pytorch-Human-Pose-Estimation#16]
Thank you very much for your contribution！What does the nModules mean？why nModules=2 ?Looking forward to your answer！

**Comment by Naman-ntc** [comment]
Hi sorry for the delay. `nModules` is number of residual blocks used in stackedHourglass. You could find use case in [the implementation](https://github.com/Naman-ntc/Pytorch-Human-Pose-Estimation/blob/master/models/StackedHourGlass.py) L#55 L#46

**Comment by wyao1459** [comment]
It 's amazing that you can remember your work a few years ago. Thank you very much for your reply!

**Comment by Naman-ntc** [comment]
Thanks you. Closing the issue
