### ISSUE TITLE
how to evaluate multi person? 

### ISSUE THREAD

**Issue by Ninebell** [Naman-ntc/Pytorch-Human-Pose-Estimation#18]
I think your code have for single person pose estimation. is there any other evaluate code for multi person pose estimation?

**Comment by Naman-ntc** [comment]
Yes currently the code only computes PCK for COCO dataset. I wrote a port long back for computing AP earlier but have lost all those files. If you are enthusiastic you can take a look at how [they](https://github.com/Microsoft/human-pose-estimation.pytorch) are computing the AP and integrate it to `metrics.py`

**Comment by Ninebell** [comment]
@Naman-ntc  thank you for your advise
