### ISSUE TITLE
Missing mpii/pureannot/train.h5

### ISSUE THREAD

**Issue by ShuangjunLiu** [Naman-ntc/Pytorch-Human-Pose-Estimation#19]
After following the instruction, I ran command 
`python main.py -DataConfig conf/datasets/mpii.defconf -ModelConfig conf/models/ChainedPredictions.defconf`

Got error: 

>  File "/scratch/liu.shu/codesPool/Pytorch-Human-Pose-Estimation/datasets/mpii.py", line 22, in __init__
    f = H.File('{}/mpii/pureannot/{}.h5'.format(self.opts.dataDir, split), 'r')
  File "/home/liu.shu/.conda/envs/pch1.5/lib/python3.8/site-packages/h5py/_hl/files.py", line 406, in __init__
...
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/scratch/liu.shu/datasets/MPII/mpii/pureannot/train.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

I didn't see the instruction how to get the mpii/pureannot/train.h5.  
Could you provide it?

**Comment by Naman-ntc** [comment]
You can download the h5 files from [here ](https://github.com/princeton-vl/pose-hg-train/tree/master/data/mpii/annot).

**Comment by ShuangjunLiu** [comment]
Thanks.
