### ISSUE TITLE
Would you explain how did you processed the mpii dataset?

### ISSUE THREAD

**Issue by CoinCheung** [Naman-ntc/Pytorch-Human-Pose-Estimation#2]
Hi, 
I do not quite understand the way you process the mpii dataset. Did you first crop the people from the image with the scale and center coordinates, and after that implement the rotate and re-scale to be the input image?

**Comment by Naman-ntc** [comment]
Hi, 
You can check [here](https://github.com/Naman-ntc/Pytorch-Human-Pose-Estimation/blob/98bc0930c38919b11f6582d0178a343c1a6af90b/datasets/mpii.py#L47) we obtain the scale center and joint coordinates from a h5 file. 
Using these (provided) parameters we implement scaling and rotations ([along with some randomness](https://github.com/Naman-ntc/Pytorch-Human-Pose-Estimation/blob/98bc0930c38919b11f6582d0178a343c1a6af90b/datasets/mpii.py#L64))
