### ISSUE TITLE
quarter shift like in "Stacked Hourglass Networks for Human Pose Estimation"

### ISSUE THREAD

**Issue by dmitrysarov** [Naman-ntc/Pytorch-Human-Pose-Estimation#20]
I did not find the implementation of heuristic mentioned in the original paper, is there any motivation to not implement it?
![image](https://user-images.githubusercontent.com/19648595/88634184-b824bb00-d0be-11ea-9810-4b3c3be791c5.png)

**Comment by Naman-ntc** [comment]
Hi, I have not implemented the quarter shift.
