### ISSUE TITLE
how  can I train deeppose with muti-gpu?

### ISSUE THREAD

**Issue by wongkwan** [Naman-ntc/Pytorch-Human-Pose-Estimation#21]
I  want to train deeppose with muti-gpu, what should I do? I try change gpu id to 0, 1, 2, 3, but it is not available. Thank you so much if you can help me !

**Comment by Naman-ntc** [comment]
Hi, the current codebase does not support multi GPU training. You can try enclosing the model with `DataParallel` ([https://pytorch.org/docs/master/generated/torch.nn.DataParallel.html](link)) and see if multi-gpu training works. 

Feel free to open the issue again if facing any further issues.
