### ISSUE TITLE
Can you add new performance metrics

### ISSUE THREAD

**Issue by wongkwan** [Naman-ntc/Pytorch-Human-Pose-Estimation#22]
Can you provide implement code for showing the MAP performance on the COCO dataset? Thank you very much if you can help me !!

**Comment by Naman-ntc** [comment]
Hi, to compute COCO MAP you cannot compute it at every iteration since COCOEval computes evaluation on entire dataset at once. Plus since this repo does single person pose estimation MAP evaluation does not fit perfectly with the current scripts. Check #18 to see guidelines about MAP
