### ISSUE TITLE
9

### ISSUE THREAD

**Issue by Wu-Jin-tao** [Naman-ntc/Pytorch-Human-Pose-Estimation#23]
9

**Comment by Naman-ntc** [comment]
Hi, Yes you can modify the source code to perform hand pose estimation. However given this is primarily a full-body human pose estimation repository, you would be better off using some hand-pose specific project.

**Comment by Wu-Jintao** [comment]
I mean, can I train the Hourglass Networks for hand posture estimation?
 will it be successful?

**Comment by Wu-Jintao** [comment]
thank you
