### ISSUE TITLE
Download link pre-trained models outdated

### ISSUE THREAD

**Issue by Archjbald** [Naman-ntc/Pytorch-Human-Pose-Estimation#24]
Hello,

first of all, thank you for all this work. I know this repo is two years old, but it seems that the link https://www.cse.iitb.ac.in/~namanjain/models.zip is a dead link. I was wondering if you could re-upload the pre-trained models.

Thank you for your help.

**Comment by GodDongWHU** [comment]
Hello, did you find this zip file ？

**Comment by Archjbald** [comment]
> Hello, did you find this zip file ？

HI. Unfortunately no.

**Comment by Naman-ntc** [comment]
Hi, unfortunately i couldn't find that and I don't have resources to maintain it, so I am planning to archive this repo
