### ISSUE TITLE
Predicted result for multiple people in graph

### ISSUE THREAD

**Issue by 54hg0220** [Naman-ntc/Pytorch-Human-Pose-Estimation#27]
Hi,

I have noted the MPII-Dataset labels only contains one data for each joint.

I am wondering how do you label 2 or more people on one image ? How do you represent it in the label?

Also, if possible. Could you please advise how do you evaluate your model accuracy?

Thanks

**Comment by Naman-ntc** [comment]
Hi, 
This repository is meant for single-person pose estimation only and assumes a bounding box cropped human as input. For that we use PCKh metric (although now multi-person pose estimation systems are quite common which use OKS metric)
