### ISSUE TITLE
The link of downloading worldCoods.mat and headsize.mat doesn't work

### ISSUE THREAD

**Issue by mz233** [Naman-ntc/Pytorch-Human-Pose-Estimation#28]
@Naman-ntc  Hi, just as it is seen in the repo "Also please download and unzip this folder and updates the paths for worldCoors & headSize in the config file." When i click the "this folde" you provided , it seems to tell 404 code. Can I get the worldCoods.mat and headsize.mat in any other way?

**Comment by Naman-ntc** [comment]
Hi, I am no longer maintaining this repo and have lost access to those folders.
