### ISSUE TITLE
How to use pretrained models?

### ISSUE THREAD

**Issue by hiepph** [Naman-ntc/Pytorch-Human-Pose-Estimation#3]
Hi, your README doesn't include how to load pretrained models and infer with a test image. Can you update or show an example here?

**Comment by Naman-ntc** [comment]
Hi,
* First you'll have to load a pretrained model `loaded_model = Model.load_state_dict(torch.load(path))`
* Center crop the image (human body inside a 256x256 window centered)
* Run evaluation using `loaded_model(image)` and use `prediction` as [here](https://github.com/Naman-ntc/Pytorch-Human-Pose-Estimation/blob/98bc0930c38919b11f6582d0178a343c1a6af90b/metrics.py#L83) depending on the model you load. That should be sufficient I believe
