### ISSUE TITLE
Inference with CPU

### ISSUE THREAD

**Issue by BaRdia-eSm** [Naman-ntc/Pytorch-Human-Pose-Estimation#8]
Hi.
I read issue #3 (https://github.com/Naman-ntc/Pytorch-Human-Pose-Estimation/issues/3) on using pretrained models so I tried to do as you mentioned in the issue:

![Screenshot from 2019-06-25 21-20-30](https://user-images.githubusercontent.com/29665874/60117374-3497ec80-978f-11e9-8b20-e414f4af963e.png)

However, I get this error:

![Screenshot from 2019-06-25 21-22-58](https://user-images.githubusercontent.com/29665874/60117611-98bab080-978f-11e9-99c3-1cf472d7ddd3.png)

Since I can not use a gpu. I was wondering if inference is possible with CPU only.
If so, i would really appreciate it that you explain where i'm doing wrong

**Comment by Naman-ntc** [comment]
I realize, the dataloader for coco (check `datasets/COCO` folder) requires gpu. Therefore it throws the provided error. 
In case you want to use dataloader for MPII a hack could be to remove certain includes from coco.py in `datasets` folder (you may need to handle other errors of class not defined which can be done via creating temoporaly classes!)

**Comment by BaRdia-eSm** [comment]
Oh I understand

Thank you
Regards

**Comment by GZP123** [comment]
Thank you for this problem you raise. My bug is similar to yours and Naman-ntc suggests me to look at here. 
This is my bug:
![image](https://user-images.githubusercontent.com/22268127/67347734-84d45f00-f575-11e9-9256-4c6ec64129e3.png)
Similar bug appears when I add the "gpu_nms.hpp" into the path that I get from the image. And I have 2 GTX 1080 GPUs and Ubuntu 16.0 and other nets can run. So do you have suggestions for this bug?
I am waitting for your reply. Thanks so much. 😊
