### ISSUE TITLE
Time consuming in pose attention

### ISSUE THREAD

**Issue by 738654805** [Naman-ntc/Pytorch-Human-Pose-Estimation#9]
Thanks for your excellent works. But it is time consuming in pose attention comparing with the lua-torch version, more specifically，the AttentionIter(). Is there something wrong?

**Comment by Naman-ntc** [comment]
Hi, I am not sure of the reason as I haven't used the lua version personally. Although as I have mentioned on `README` I couldn't reproduce their results with my implementation and I can't comment on it right now.

**Comment by aFewThings** [comment]
@Naman-ntc Did you solve your problem? I also implemented with pytorch in my self, and it seems that model begins to overfit almost 30 epochs.

**Comment by Naman-ntc** [comment]
Hi no, I am not aware of the reason and have not looked into it.

**Comment by aFewThings** [comment]
@Naman-ntc  Thank you.
